version: "3"
services:
    xampp:
        image: tomsik68/xampp
        restart: always        
        ports:
            - "801:80"
        volumes:
            - ./formularios:/www
            - ./db:/var/lib/mysql
